name: 'Terraform'
on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::811352020564:role/terraform-s3-deployer-role
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Import Role
        # This checks if the role is already in state. 
        # If not, it imports it. If yes, it just echoes.
        run: |
          terraform state show aws_iam_role.existing_role || terraform import aws_iam_role.existing_role terraform-s3-deployer-role

      - name: Terraform Plan
        run: terraform plan